test

diff --git a/.github/workflows/postgresql_migration.yml b/.github/workflows/postgresql_migration.yml
--- a/.github/workflows/postgresql_migration.yml
+++ b/.github/workflows/postgresql_migration.yml
@@ -39,11 +39,11 @@ jobs:
 
       - name: Execute script1.ddl on PostgreSQL1
         run: |
-          PGPASSWORD=your_password psql -h localhost -U postgres -d postgres -p 5432 -c "create table A (id integer, name varchar(20));insert into A values(1,'ray');"
+          PGPASSWORD=your_password psql -h localhost -U postgres -d postgres -p 5432 -c "create table A (id integer, name varchar(20));"
 
       - name: Execute script2.ddl on PostgreSQL2
         run: |
-          PGPASSWORD=your_password psql -h localhost -U postgres -d postgres -p 5433 -c "create table A (id integer, name varchar(20));"
+          PGPASSWORD=your_password psql -h localhost -U postgres -d postgres -p 5433 -c "create table A (id integer);"
 
       - name: Install Migra
         run: pip install migra[pg]
@@ -54,22 +54,22 @@ jobs:
       - name: View migration output
         run: cat migration_script.sql
 
-      - name: Run Migra migration script
-        run: psql postgresql://postgres:your_password@localhost:5433/postgres -1 -f migration_script.sql
-
-      - name: Verify Migration Result
-        run: |
-          echo "Checking row count in Database 1"
-          ROW_COUNT_DB1=$(docker exec ${{ job.services.postgres1.id }} psql -U postgres -t -c "SELECT COUNT(*) FROM A;")
-          echo "Row count in Database 1: $ROW_COUNT_DB1"
-
-          echo "Checking row count in Database 2"
-          ROW_COUNT_DB2=$(docker exec ${{ job.services.postgres2.id }} psql -U postgres -t -c "SELECT COUNT(*) FROM A;")
-          echo "Row count in Database 2: $ROW_COUNT_DB2"
-
-          if [ "$ROW_COUNT_DB1" -eq "$ROW_COUNT_DB2" ]; then
-            echo "Row counts are equal. Migration successful."
-          else
-            echo "Row counts are not equal. Migration failed."
-            exit 1
-          fi
+#      - name: Run Migra migration script
+#        run: psql postgresql://postgres:your_password@localhost:5433/postgres -1 -f migration_script.sql
+#
+#      - name: Verify Migration Result
+#        run: |
+#          echo "Checking row count in Database 1"
+#          ROW_COUNT_DB1=$(docker exec ${{ job.services.postgres1.id }} psql -U postgres -t -c "SELECT COUNT(*) FROM A;")
+#          echo "Row count in Database 1: $ROW_COUNT_DB1"
+#
+#          echo "Checking row count in Database 2"
+#          ROW_COUNT_DB2=$(docker exec ${{ job.services.postgres2.id }} psql -U postgres -t -c "SELECT COUNT(*) FROM A;")
+#          echo "Row count in Database 2: $ROW_COUNT_DB2"
+#
+#          if [ "$ROW_COUNT_DB1" -eq "$ROW_COUNT_DB2" ]; then
+#            echo "Row counts are equal. Migration successful."
+#          else
+#            echo "Row counts are not equal. Migration failed."
+#            exit 1
+#          fi
