test

diff --git a/.github/workflows/postgresql_migration.yml b/.github/workflows/postgresql_migration.yml
--- a/.github/workflows/postgresql_migration.yml
+++ b/.github/workflows/postgresql_migration.yml
@@ -50,3 +50,20 @@ jobs:
 
       - name: Run Migra migration
         run: migra --unsafe postgresql://postgres:your_password@localhost:5432/postgres postgresql://postgres:your_password@localhost:5433/postgres
+
+      - name: Verify Migration Result
+        run: |
+          echo "Checking row count in Database 1"
+          ROW_COUNT_DB1=$(docker exec postgres1 psql -U postgres -t -c "SELECT COUNT(*) FROM A;")
+          echo "Row count in Database 1: $ROW_COUNT_DB1"
+          
+          echo "Checking row count in Database 2"
+          ROW_COUNT_DB2=$(docker exec postgres2 psql -U postgres -t -c "SELECT COUNT(*) FROM A;")
+          echo "Row count in Database 2: $ROW_COUNT_DB2"
+          
+          if [ "$ROW_COUNT_DB1" -eq "$ROW_COUNT_DB2" ]; then
+            echo "Row counts are equal. Migration successful."
+          else
+            echo "Row counts are not equal. Migration failed."
+            exit 1
+          fi
